tap "adoptopenjdk/openjdk"
tap "bramstein/webfonttools"
tap "buo/cask-upgrade"
tap "cjbassi/ytop"
tap "derailed/k9s"
tap "dteoh/sqa"
tap "fabianishere/personal"
tap "getantibody/tap"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "joedrago/repo"
tap "louisbrunner/valgrind"
tap "teamookla/speedtest"
brew "ack"
brew "annie"
brew "xz"
brew "ansible"
brew "ansible-lint"
brew "webp"
brew "gmp"
brew "asciinema"
brew "python@3.9"
brew "glib"
brew "autossh"
brew "awscli"
brew "azure-cli"
brew "b2-tools"
brew "bash"
brew "bat"
brew "bfg"
brew "binutils"
brew "tcl-tk"
brew "cairo"
brew "gobject-introspection"
brew "harfbuzz"
brew "libraqm"
brew "numpy"
brew "pillow"
brew "binwalk"
brew "blueutil"
brew "caddy", restart_service: true
brew "carthage"
brew "chezmoi"
brew "cifer"
brew "coreutils"
brew "cowsay"
brew "create-dmg"
brew "ctags"
brew "dex2jar"
brew "diff-so-fancy"
brew "dns2tcp"
brew "dockutil"
brew "entr"
brew "exa"
brew "fasd"
brew "fd"
brew "unbound", restart_service: true
brew "gnutls"
brew "libass"
brew "libsodium"
brew "srt"
brew "ffmpeg"
brew "flarectl"
brew "foremost"
brew "fstrm"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gnu-sed"
brew "gnu-tar"
brew "pinentry"
brew "gnupg"
brew "go"
brew "netpbm"
brew "gocr"
brew "gotop"
brew "grep"
brew "gsettings-desktop-schemas"
brew "pango"
brew "gtk+"
brew "gtk+3"
brew "hashpump"
brew "helm"
brew "hey"
brew "hopenpgp-tools"
brew "hstr"
brew "htop"
brew "httpie"
brew "hub"
brew "hugo"
brew "libssh"
brew "mysql-client"
brew "hydra"
brew "libheif"
brew "imagemagick"
brew "iperf3"
brew "jc"
brew "jq"
brew "knock"
brew "protobuf-c"
brew "knot", restart_service: true
brew "kubectx"
brew "kustomize"
brew "ldns"
brew "libfido2"
brew "libimobiledevice"
brew "libirecovery"
brew "libpq"
brew "libproxy"
brew "locateme"
brew "lolcat"
brew "lsd"
brew "lua"
brew "lynx"
brew "m-cli"
brew "ruby"
brew "macvim"
brew "magic-wormhole"
brew "mas"
brew "mitmproxy"
brew "mono"
brew "mosh"
brew "mtr"
brew "ncdu"
brew "neofetch"
brew "ninja"
brew "nmap"
brew "node"
brew "noti"
brew "nss"
brew "ocrad"
brew "opensc"
brew "openssh"
brew "optipng"
brew "osx-cpu-temp"
brew "php", restart_service: true
brew "pigz"
brew "pinentry-mac"
brew "pngcheck"
brew "procs"
brew "putty"
brew "pv"
brew "python@3.8"
brew "qt"
brew "r"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "rename"
brew "rlwrap"
brew "screen"
brew "skaffold"
brew "sleepwatcher", restart_service: true
brew "slides"
brew "socat"
brew "sqlmap"
brew "ssh-copy-id"
brew "stress"
brew "subversion"
brew "tcpflow"
brew "tcpreplay"
brew "tcptrace"
brew "telnet"
brew "terminal-notifier"
brew "terraform"
brew "testssl"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tree"
brew "ucspi-tcp"
brew "vbindiff"
brew "velero"
brew "wakeonlan"
brew "wget"
brew "whatmask"
brew "wifi-password"
brew "wimlib"
brew "wireguard-tools"
brew "woff2"
brew "xpdf"
brew "yamllint"
brew "yarn"
brew "ykman"
brew "ykpers"
brew "youtube-dl"
brew "yubico-piv-tool"
brew "zopfli"
brew "zsh"
brew "bramstein/webfonttools/sfnt2woff"
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "cjbassi/ytop/ytop"
brew "derailed/k9s/k9s"
brew "fabianishere/personal/pam_reattach"
brew "hashicorp/tap/nomad"
brew "heroku/brew/heroku"
brew "joedrago/repo/avifenc"
brew "louisbrunner/valgrind/valgrind", args: ["HEAD"]
brew "teamookla/speedtest/speedtest"
cask "1password"
cask "1password-cli"
cask "adoptopenjdk"
cask "aws-vault"
cask "backblaze"
cask "balenaetcher"
cask "cloudflare-warp"
cask "daisydisk"
cask "discord"
cask "docker"
cask "dropbox"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-menlo-for-powerline"
cask "font-source-code-pro"
cask "font-source-han-sans"
cask "font-source-han-serif"
cask "google-chrome"
cask "google-cloud-sdk"
cask "handbrake"
cask "iina"
cask "imazing"
cask "iterm2"
cask "key-codes"
cask "krisp"
cask "launchbar"
cask "linkliar"
cask "macmediakeyforwarder"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "mounty"
cask "nrlquaker-winbox"
cask "obsidian"
cask "parsec"
cask "powershell"
cask "qq"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookapk"
cask "rectangle"
cask "skype"
cask "slowquitapps"
cask "spotify"
cask "sublime-text"
cask "suspicious-package"
cask "teamviewer"
cask "telegram"
cask "transmit"
cask "typora"
cask "ueli"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "wechat"
cask "wireshark"
cask "yo"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "AutoSwitchInput", id: 1470350547
mas "Craft", id: 1487937127
mas "DevCleaner", id: 1388020431
mas "GoodNotes", id: 1444383602
mas "iStudiez Pro", id: 402989379
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Metronome X", id: 1222424189
mas "Microsoft Excel", id: 462058435
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "MoneyWiz", id: 1511185140
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "Tab Space", id: 1473726602
mas "Tailscale", id: 1475387142
mas "Tweetbot", id: 1384080005
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
