#!/usr/bin/env zsh

# `shell_env.sh` is a main file for any general-case utils.
#
# This file is used as a source file for zsh.

source "$HOME/.shell/aliases.zsh"
source "$HOME/.shell/functions.zsh"
source "$HOME/.shell/external.zsh"

# === Local variables and overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi
