#!/usr/bin/env zsh

# `shell_env.sh` is a main file for any general-case utils.
#
# This file is used as a source file for zsh.

# === Plugin management ===
# Run this after adding a plugin. This reads from ~/.zsh_plugins.txt to generate static loading script ~/.zsh_plugins.sh
# antibody bundle < "$HOME/.zsh_plugins.txt" > "$HOME/.zsh_plugins.sh"

source "$HOME/.zsh_plugins.sh"

# === Other shell parts ===

source "$HOME/.shell/.aliases"
source "$HOME/.shell/.functions"
source "$HOME/.shell/.external"

# === Local variables and overrides ===

if [[ -f "$HOME/.shell_env_local" ]]; then
  source "$HOME/.shell_env_local"
fi
