# OrbStack NixOS configuration
# OrbStack manages the container lifecycle, we configure NixOS inside it
{
  config,
  pkgs,
  modulesPath,
  currentSystemUser,
  ...
}:
{
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    /etc/nixos/incus.nix
    # Include the OrbStack-specific configuration.
    /etc/nixos/orbstack.nix
  ];

  users.users.${currentSystemUser} = {
    uid = 501; # Match macOS user UID for seamless file sharing
    extraGroups = [
      "wheel"
      "orbstack"
    ];

    # Simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/${currentSystemUser}";
    homeMode = "700";
    useDefaultShell = true;

    # Set zsh as the default shell (OrbStack defaults to bash)
    shell = pkgs.zsh;
  };

  # Enable zsh system-wide to support home-manager zsh configuration
  programs.zsh.enable = true;

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Europe/Rome";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # System packages
  environment.systemPackages = with pkgs; [
    ghostty.terminfo
  ];

  system.stateVersion = "25.11";
}
